module.exports = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  DUPLICATE_ERROR: "DUPLICATE_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INVALID_ID: "INVALID_ID",
  DATA_FETCH_ERROR: "DATA_FETCH_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN"
};